services:
  vpinformatics-portfolio:
    image: ghcr.io/vpinformatics/portfolio_2026:latest
    container_name: vpinformatics-portfolio
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vpinformatics-portfolio.rule=Host(`vpinformatics.in`) || Host(`www.vpinformatics.in`)"
      - "traefik.http.routers.vpinformatics-portfolio.entrypoints=websecure"
      - "traefik.http.routers.vpinformatics-portfolio.tls=true"
      - "traefik.http.routers.vpinformatics-portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.vpinformatics-portfolio.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
